In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
songs=pd.read_csv("Spotify-2000.csv")

In [3]:
songs.head()


Index                   Title             Artist            Top_Genre  \
0      1                 Sunrise        Norah Jones      adult standards   
1      2             Black Night        Deep Purple           album rock   
2      3          Clint Eastwood           Gorillaz  alternative hip hop   
3      4           The Pretender       Foo Fighters    alternative metal   
4      5  Waitin' On A Sunny Day  Bruce Springsteen         classic rock   

   Year  Beats_Per_Minute (BPM)  Energy  Danceability  Loudness(dB)  Liveness  \
0  2004                     157      30            53           -14        11   
1  2000                     135      79            50           -11        17   
2  2001                     168      69            66            -9         7   
3  2007                     173      96            43            -4         3   
4  2002                     106      82            58            -5        10   

   Valence Length(Duration)  Acousticness  Speechiness  Popularity  
0       68              201            94            3          71  
1       81              207            17            7          39  
2       52              341             2           17          69  
3       37              269             0            4          76  
4       87              256             1            3          59

In [4]:
songs.tail()

Index             Title                    Artist        Top_Genre  \
1989   1990  Heartbreak Hotel             Elvis Presley  adult standards   
1990   1991         Hound Dog             Elvis Presley  adult standards   
1991   1992   Johnny B. Goode               Chuck Berry       blues rock   
1992   1993         Take Five  The Dave Brubeck Quartet            bebop   
1993   1994    Blueberry Hill               Fats Domino  adult standards   

      Year  Beats_Per_Minute (BPM)  Energy  Danceability  Loudness(dB)  \
1989  1958                      94      21            70           -12   
1990  1958                     175      76            36            -8   
1991  1959                     168      80            53            -9   
1992  1959                     174      26            45           -13   
1993  1959                     133      50            49           -10   

      Liveness  Valence Length(Duration)  Acousticness  Speechiness  \
1989        11       72              128            84            7   
1990        76       95              136            73            6   
1991        31       97              162            74            7   
1992         7       60              324            54            4   
1993        16       83              148            74            3   

      Popularity  
1989          63  
1990          69  
1991          74  
1992          65  
1993          56

In [5]:
songs.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Index                   1994 non-null   int64 
 1   Title                   1994 non-null   object
 2   Artist                  1994 non-null   object
 3   Top_Genre               1994 non-null   object
 4   Year                    1994 non-null   int64 
 5   Beats_Per_Minute (BPM)  1994 non-null   int64 
 6   Energy                  1994 non-null   int64 
 7   Danceability            1994 non-null   int64 
 8   Loudness(dB)            1994 non-null   int64 
 9   Liveness                1994 non-null   int64 
 10  Valence                 1994 non-null   int64 
 11  Length(Duration)        1994 non-null   object
 12  Acousticness            1994 non-null   int64 
 13  Speechiness             1994 non-null   int64 
 14  Popularity              1994 non-null   int64 
dtypes: i

In [6]:
songs.isnull().sum()

Index                     0
Title                     0
Artist                    0
Top_Genre                 0
Year                      0
Beats_Per_Minute (BPM)    0
Energy                    0
Danceability              0
Loudness(dB)              0
Liveness                  0
Valence                   0
Length(Duration)          0
Acousticness              0
Speechiness               0
Popularity                0
dtype: int64

In [7]:
songs.notnull().sum()

Index                     1994
Title                     1994
Artist                    1994
Top_Genre                 1994
Year                      1994
Beats_Per_Minute (BPM)    1994
Energy                    1994
Danceability              1994
Loudness(dB)              1994
Liveness                  1994
Valence                   1994
Length(Duration)          1994
Acousticness              1994
Speechiness               1994
Popularity                1994
dtype: int64

In [8]:
songs_features=['Title','Artist','Top_Genre']
songs_features

['Title', 'Artist', 'Top_Genre']

In [9]:
songs['tags']=songs['Artist']+songs['Top_Genre']
songs.head()

Index                   Title             Artist            Top_Genre  \
0      1                 Sunrise        Norah Jones      adult standards   
1      2             Black Night        Deep Purple           album rock   
2      3          Clint Eastwood           Gorillaz  alternative hip hop   
3      4           The Pretender       Foo Fighters    alternative metal   
4      5  Waitin' On A Sunny Day  Bruce Springsteen         classic rock   

   Year  Beats_Per_Minute (BPM)  Energy  Danceability  Loudness(dB)  Liveness  \
0  2004                     157      30            53           -14        11   
1  2000                     135      79            50           -11        17   
2  2001                     168      69            66            -9         7   
3  2007                     173      96            43            -4         3   
4  2002                     106      82            58            -5        10   

   Valence Length(Duration)  Acousticness  Speechiness  Popularity  \
0       68              201            94            3          71   
1       81              207            17            7          39   
2       52              341             2           17          69   
3       37              269             0            4          76   
4       87              256             1            3          59   

                            tags  
0     Norah Jonesadult standards  
1          Deep Purplealbum rock  
2    Gorillazalternative hip hop  
3  Foo Fightersalternative metal  
4  Bruce Springsteenclassic rock

In [10]:
combine=songs.drop(columns=['Artist','Top_Genre','Year','Beats_Per_Minute (BPM)','Energy','Danceability','Loudness(dB)','Liveness','Valence','Length(Duration)','Acousticness','Speechiness','Popularity'])

In [11]:
combine.head()

Index                   Title                           tags
0      1                 Sunrise     Norah Jonesadult standards
1      2             Black Night          Deep Purplealbum rock
2      3          Clint Eastwood    Gorillazalternative hip hop
3      4           The Pretender  Foo Fightersalternative metal
4      5  Waitin' On A Sunny Day  Bruce Springsteenclassic rock

In [12]:
combine.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Index   1994 non-null   int64 
 1   Title   1994 non-null   object
 2   tags    1994 non-null   object
dtypes: int64(1), object(2)
memory usage: 46.9+ KB


In [13]:
combine.iloc[0].tags

'Norah Jonesadult standards'

In [14]:
cv=CountVectorizer()

In [15]:
vectors=cv.fit_transform(combine['tags']).toarray()

In [16]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
similarity=cosine_similarity(vectors)

In [18]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.33333333],
       [0.        , 1.        , 0.        , ..., 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.33333333, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [19]:
similarity[0]

array([1.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.33333333])

In [ ]:
len(similarity[0])

in similarity it is showing the similarity of one song with all the other songs

In [ ]:
def recommend(song):
    song_index=combine[combine['Title']==song].index[0]
    distance=sorted(list(enumerate(similarity[song_index])),reverse=True,key=lambda x:x[1])
    for i in distance[1:6]:
        print(combine.iloc[i[0]].Title)

In [ ]:
recommend('Black Night')

In [ ]:
import pickle


In [ ]:
pickle.dump(combine,open('song.sav','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.sav','wb'))